import { test } from '@playwright/test';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { applyShot, bootOcean, capture } from './lib/capture';
import { encodePng } from './lib/png';
import { SHOTS, type Shot } from './lib/shots';
import { describeStack, isSoftwareRenderer } from './lib/stack';

/**
 * Regenerates the README's gallery images.
 *
 * Opt-in — `CAPTURE_GALLERY=1 npx playwright test --project=visual gallery` —
 * because it writes into `docs/`, which no ordinary test run should do.
 *
 * It exists at all because the gallery had gone stale: the images were captured
 * by hand months before the renderer they were supposed to be showing, and
 * nothing could tell. Running through the same deterministic harness the visual
 * baselines use means a gallery image is reproducible from a commit, frames
 * exactly what the shot list says it frames, and is regenerated by one command
 * when the renderer changes.
 *
 * Scene shots come from `capturePixels`, which renders the post chain into an
 * offscreen target — so the DOM overlay is not in them by construction, and no
 * hiding is required. The interface shot is the one exception and uses a
 * compositor screenshot precisely *because* it is about the overlay.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const IMAGE_DIR = join(HERE, '..', 'docs', 'images');

/**
 * 1600x900, not the baselines' 1280x720.
 *
 * Same 16:9, so every shot frames identically and the pinned cameras carry over
 * unchanged; the extra pixels are for a reader looking at the image full size on
 * a README rather than for a metric.
 */
const GALLERY_VIEWPORT = { width: 1600, height: 900 } as const;

/** A gallery entry: a canonical shot, or a variation defined here. */
interface GalleryShot {
  /** Output file name, without extension. */
  file: string;
  shot: Shot;
}

function canonical(id: string, file: string): GalleryShot {
  const shot = SHOTS.find((s) => s.id === id);
  if (shot === undefined) throw new Error(`gallery: no canonical shot "${id}"`);
  return { file, shot };
}

/**
 * Moonlit has no canonical shot — the visual suite covers the night path through
 * the preset-distinctness test rather than a baseline, since a near-black frame
 * is a poor regression target. It is worth a gallery image regardless.
 */
const MOONLIT: Shot = {
  id: 'gallery-moonlit',
  title: 'Moonlit',
  purpose: 'Gallery only.',
  state: {
    quality: 'ultra',
    cameraMode: 'orbit',
    windSpeed: 9,
    peakWavelength: 60,
    cloudCoverage: 0.25,
    preset: 'moonlit',
  },
  camera: { position: [-38, 12, 52], target: [0, 3, 0] },
  time: 18,
  settleSteps: 90,
};

const GALLERY: readonly GalleryShot[] = [
  // The README's opening image. `clear-day-wide` used to be built into `hero`
  // and the README referenced it nowhere, so the slot was published and unused.
  canonical('ship-and-island', 'hero'),
  canonical('clear-day-wide', 'clear-day'),
  canonical('storm', 'storm'),
  canonical('sunset', 'sunset'),
  { file: 'moonlit', shot: MOONLIT },
  canonical('near-water-detail', 'waves'),
  canonical('underwater', 'underwater'),
  canonical('boat-chase', 'boat'),
  canonical('island-approach', 'island'),
  canonical('shore-break', 'shore'),
  canonical('reef-dive', 'reef'),
  // Beats of the tour, captured by *running* the flight rather than by copying
  // its camera into an orbit shot — which for these is the difference between
  // the picture and a lie, since a night beat photographed under the preset's
  // own sun is a noon frame at a night camera position.
  //
  // `landfall` replaces what used to be `surf` here. The 60-second flight stands
  // half a kilometre off the island by design, so it has no surf beat left to
  // photograph — and the gallery already carried the shore break twice, once
  // from the tour and once from the canonical `shore-break` shot below. This
  // slot now shows the thing the re-cut tour actually does.
  canonical('cinematic-landfall', 'landfall'),
  canonical('cinematic-squall', 'squall'),
  canonical('cinematic-night', 'night'),
  // `waterline` is deliberately absent. The per-pixel split is a real capability
  // and the canonical shot regression-tests it, but the image it produces is a
  // pale wash that sells it badly — and publishing a weak picture to advertise a
  // feature is the same mistake as publishing a stale one.
];

test.describe('gallery', () => {
  test.skip(process.env.CAPTURE_GALLERY !== '1', 'set CAPTURE_GALLERY=1 to regenerate docs/images');

  test('captures the README gallery', async ({ page }) => {
    // Twenty-five minutes, up from fifteen. Not a symptom being papered over:
    // a gallery shot is a boot, a preset change, ninety settle steps and a
    // warm-up capture at 1600x900, and the renderer this suite photographs now
    // carries a volumetric cloud layer that reaches the horizon, an aerial
    // perspective on every material and a heightfield shadow on the island. The
    // *frame* budget is measured by `npm run bench` and passes with margin; this
    // number is about how long sixteen full boots take, which is a different
    // quantity and has never been a gate.
    test.setTimeout(1_500_000);
    await page.setViewportSize(GALLERY_VIEWPORT);
    await bootOcean(page);

    // The gallery is *published*, so a software-rasterised capture would put a
    // picture of the fallback path on the front page of the repository.
    const stack = await describeStack(page);
    test.skip(
      isSoftwareRenderer(stack.gpu),
      `gallery capture needs a real GPU; this run is on ${stack.gpu}`,
    );

    mkdirSync(IMAGE_DIR, { recursive: true });

    for (const { file, shot } of GALLERY) {
      // A fresh page per image.
      //
      // `resetDeterministic` does not make a shot completely independent of the
      // one before it — capturing the boat shot straight after the storm gives
      // visibly heavier foam than capturing it first, so something in the sea
      // state survives the reset. That is a real defect in the reset path and it
      // is recorded as one; what it must not do is decide what the front page of
      // the repository looks like. Reloading costs a few seconds per image and
      // removes the entire class from the published output.
      await page.goto('/?gate=0&quality=high');
      await bootOcean(page);
      await applyShot(page, shot);
      const image = await capture(page);
      writeFileSync(join(IMAGE_DIR, `${file}.png`), encodePng(image));
      console.log(`[gallery] ${file}.png  ${image.width}x${image.height}  (${shot.id})`);
    }

    // The interface shot, with the overlay: a compositor screenshot rather than
    // a render, because the panel and HUD are DOM.
    await page.goto('/?gate=0&quality=high');
    await bootOcean(page);
    await applyShot(page, SHOTS[0]);
    await page.evaluate(() => window.__ocean.setState({ buoyancyProbes: true }));
    // The probes are geometry, so they need a frame to appear.
    await page.evaluate(() => window.__ocean.step(1 / 60, 2));
    const ui = await page.screenshot({ animations: 'disabled' });
    writeFileSync(join(IMAGE_DIR, 'interface.png'), ui);
    await page.evaluate(() => window.__ocean.setState({ buoyancyProbes: false }));
    console.log('[gallery] interface.png');
  });
});
